
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zotprime-elasticsearch
  namespace: zotprime
  labels:
#    component: elasticsearch
    apps: zotprime-elasticsearch
spec:
  selector:
    matchLabels:
      apps: zotprime-elasticsearch
  serviceName: "elasticsearch-masterservice"
  replicas: 1
  template:
    metadata:
      labels:
        apps: zotprime-elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: uniuu/zotprime-elasticsearch:v2.7.0
        env:
        - name: CLUSTER_NAME
          value: zotero
        - name: xpack.security.enabled
          value: "true"
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: "false"
        - name: discovery.type
          value: single-node
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: dataes
          mountPath: /data
      priorityClassName: high-priority
  volumeClaimTemplates:
  - metadata:
      name: dataes
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 2Gi
