version: '3.9'
services:
  zotprime-db:
    image: "zotprime-db:${VER}"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MARIADB_DATABASE=${MYSQLDATABASE}
      - MARIADB_USER=${MYSQLUSER}
      - MARIADB_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
  zotprime-elasticsearch:
    image: "zotprime-elasticsearch:${VER}"
    environment:
      - cluster.name=zotero
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-redis:
    image: "zotprime-redis:${VER}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-memcached:
    image: "zotprime-memcached:${VER}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-localstack:
    image: "zotprime-localstack:${VER}"
    environment:
      - SERVICES=sns,sqs,apigateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-minio:
    image: "zotprime-minio:${VER}"
    environment:
      - MINIO_ROOT_USER=${MINIOROOTUSER}
      - MINIO_ROOT_PASSWORD=${MINIOROOTPASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-dataserver:
    image: "zotprime-dataserver:${VER}"
    ports:
      - "8080:80"
      - "8082:8082"
    volumes:
      - "./dataserver/:/var/www/zotero:rw"
      - "./Zend/:/var/www/zotero/include/Zend:rw"
      - "./docker/dataserver/create-user.sh:/var/www/zotero/admin/create-user.sh:ro" 
      - "./docker/dataserver/config.inc.php:/var/www/zotero/include/config/config.inc.php:ro"
      - "./docker/dataserver/dbconnect.inc.php:/var/www/zotero/include/config/dbconnect.inc.php:ro"
      - "./docker/dataserver/header.inc.php:/var/www/zotero/include/header.inc.php:ro"
      - "./docker/dataserver/Storage.inc.php:/var/www/zotero/model/Storage.inc.php:ro"    
      - "./docker/db/init-mysql.sh:/var/www/zotero/misc/init-mysql.sh:ro"
      - "./docker/db/db_update.sh:/var/www/zotero/misc/db_update.sh:ro"
      - "./docker/db/www.sql:/var/www/zotero/misc/www.sql:ro"
      - "./docker/db/shard.sql:/var/www/zotero/misc/shard.sql:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - RUN_USER=apache
      - RUN_GROUP=apache
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached 
      - zotprime-tinymceclean
      - zotprime-streamserver
    links:
      - zotprime-db:mysql
      - zotprime-elasticsearch:elasticsearch
      - zotprime-redis:redis
      - zotprime-memcached:memcached
      - zotprime-localstack:localstack
      - zotprime-minio:minio
      - zotprime-tinymceclean:tinymceclean
      - zotprime-streamserver:streamserver
    restart: always
  zotprime-tinymceclean:
    image: "zotprime-tinymceclean:${VER}"
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached
    links:
      - zotprime-redis:redis 
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
  zotprime-streamserver:
    image: "zotprime-streamserver:${VER}"
    ports:
      - "8081:81"
    volumes:
      - "./docker/stream-server/default.js:/usr/src/app/config/default.js:ro"
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached 
    links:
      - zotprime-redis:redis
  zotprime-phpmyadmin:
    image: "zotprime-phpmyadmin:${VER}"
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
    links:
      - zotprime-db:mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
volumes:
  dbdata:
   driver: local

