version: '3.9'
services:
  zotprime-db:
    image: mariadb:10
   # command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MYSQL_DATABASE=${MYSQLDATABASE}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
  zotprime-elasticsearch:
#   image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - cluster.name=zotero
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false 
       #     - cluster.routing.allocation.disk.watermark.flood_stage=500mb
      - discovery.type=single-node
    volumes:
      - /etc/localtime:/etc/localtime:ro
#   privileged: true
   #user: root
   #command: "sysctl -w vm.max_map_count=262144 && su elasticsearch -c bin/elasticsearch"
 #  sysctls:
 #           - vm.max_map_count=262144
#   command: "sysctl -w vm.max_map_count=262144"
  zotprime-redis:
    image: redis:5.0
 #   privileged: true
 #    user: root
 #    sysctls:
 #      - sysctl vm.overcommit_memory=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-memcached:
    image: memcached:1.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-localstack:
    image: atlassianlabs/localstack
    environment:
      - SERVICES=sns,sqs,apigateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-minio:
    build:
      context: .
      dockerfile: minio.Dockerfile
    environment:
      - MINIO_ACCESS_KEY=zotero
      - MINIO_SECRET_KEY=zoterodocker
    command: server /data
    ports:
      - "8082:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-dataserver:
    image: zotprime-dataserver
    build:
      context: .
      dockerfile: ds.Dockerfile
    ports:
      - "8080:80"
#      - "8082:8082"
    volumes:
      - "./dataserver/:/var/www/zotero:rw"
      - "./docker/dataserver/config/config.inc.php:/var/www/zotero/include/config/config.inc.php:ro"
      - "./docker/dataserver/config/dbconnect.inc.php:/var/www/zotero/include/config/dbconnect.inc.php:ro"
      - "./Zend/:/var/www/zotero/include/Zend:rw"
      - "./docker/dataserver/config/header.inc.php:/var/www/zotero/include/header.inc.php:ro"
      - "./docker/dataserver/config/Storage.inc.php:/var/www/zotero/model/Storage.inc.php:ro"
      - "./docker/dataserver/dbinit/init-mysql.sh:/var/www/zotero/misc/init-mysql.sh:ro"
      - "./docker/dataserver/dbinit/db_update.sh:/var/www/zotero/misc/db_update.sh:ro"
      - "./docker/dataserver/dbinit/www.sql:/var/www/zotero/misc/www.sql:ro"
      - "./docker/dataserver/dbinit/shard.sql:/var/www/zotero/misc/shard.sql:ro"
      - "./docker/dataserver/config/create-user.sh:/var/www/zotero/admin/create-user.sh:ro"
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RUN_USER=apache
      - RUN_GROUP=apache
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached 
      - zotprime-tinymceclean
      - zotprime-streamserver
    links:
      - zotprime-db:mysql
      - zotprime-elasticsearch:elasticsearch
      - zotprime-redis:redis
      - zotprime-memcached:memcached
      - zotprime-localstack:localstack
      - zotprime-minio:minio
      - zotprime-tinymceclean:tinymceclean
      - zotprime-streamserver:streamserver
    restart: always
  zotprime-tinymceclean:
    image: zotprime-tinymceclean
    build:
      context: .
      dockerfile: tmcs.Dockerfile
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached
    links:
      - zotprime-redis:redis 
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
  zotprime-streamserver:
    image: zotprime-streamserver
    build:
      context: .
      dockerfile: sts.Dockerfile
    ports:
      - "8081:81"
    volumes:
      - "./docker/stream-server/default.js:/usr/src/app/config/default.js:ro"
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached 
    links:
      - zotprime-redis:redis
  zotprime-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
    links:
      - zotprime-db:mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  dbdata:
   driver: local

