apiVersion: v1
kind: Service
metadata:
  labels:
    apps: minio
  name: minio
  namespace: zotprime
spec:
  ports:
    - name: minio-ui
      port: 80
      targetPort: 9001
    - name: minio-data
      port: 9000
      targetPort: 9000
  selector:
    apps: zotprime-minio
  type: ClusterIP
status:
  loadBalancer: {}
