apiVersion: v1
kind: Service
metadata:
  labels:
    apps: phpmyadmin
  name: phpmyadmin
  namespace: zotprime
spec:
  ports:
    - name: phpmyadmin
      port: 8083
      targetPort: 80
  selector:
    apps: zotprime-phpmyadmin
  type: ClusterIP