apiVersion: v1
kind: Service
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-localstack
  labels:
    apps: localstack
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.localstack.type }}
  selector:
    apps: zotprime-localstack
  {{- include "zotprime-k8s.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.localstack.ports | toYaml | nindent 2 -}}