apiVersion: v1
kind: Service
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-minio
  labels:
    apps: minio
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.minio.type }}
  selector:
    apps: zotprime-minio
  {{- include "zotprime-k8s.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.minio.ports | toYaml | nindent 2 -}}