apiVersion: v1
kind: Service
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-phpmyadmin
  labels:
    apps: phpmyadmin
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.phpmyadmin.type }}
  selector:
    apps: zotprime-phpmyadmin
  {{- include "zotprime-k8s.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.phpmyadmin.ports | toYaml | nindent 2 -}}