apiVersion: v1
data:
  secret-minio.txt: TUlOSU9fUk9PVF9QQVNTV09SRD16b3Rlcm9kb2NrZXIK
kind: Secret
metadata:
  name: minio-secret
  namespace: zotprime
type: Opaque

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: zotprime
data:
  minio-user: zotero

---
apiVersion: v1
kind: Service
metadata:
  labels:
    apps: minio
  name: minio
  namespace: zotprime
spec:
  clusterIP: 10.152.183.11
  ports:
    - name: minio-ui
      port: 9001
      targetPort: 9001
    - name: minio-data
      port: 9000
      targetPort: 9000
    - name: minio-data2
      port: 80
      targetPort: 9000
  selector:
    apps: zotprime-minio
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataminio
  namespace: zotprime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: zotprime-minio
  name: zotprime-minio
  namespace: zotprime
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: zotprime-minio
  strategy: {}
  template:
    metadata:
      labels:
        apps: zotprime-minio
      name: zotprime-minio
    spec:
      containers:
        - name: zotprime-minio
          image: uniuu/zotprime-minio:v2.7.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
              cpu: "0.5"
          command:
            - /bin/bash
            - -c
          args: 
            -  set -o allexport && source tmp/_key/secret-minio.txt && set +o allexport && minio server /data --console-address :9001 
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 20
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /minio/health/live
              port: 9000
          ports:
            - containerPort: 9000
              name: data
            - containerPort: 9001
              name: ui
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                 configMapKeyRef:
                   name: minio-config
                   key: minio-user
          volumeMounts:
            - name: s3data
              mountPath: /data
            - name: minio-secret
              mountPath: "/tmp/_key"
              readOnly: true
        - name: zotprime-miniomc
          image: uniuu/zotprime-miniomc:v2.7.0
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - name: s3data
              mountPath: /data
            - name: minio-secret
              mountPath: "/tmp/_key"
              readOnly: true
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: minio-user
      priorityClassName: high-priority
      restartPolicy: Always
      securityContext: {}
      volumes:
        - name: s3data
          persistentVolumeClaim:
            claimName: dataminio
        - name: minio-secret
          secret:
            secretName: minio-secret
status: {}
