
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: zotprime-k8s
    name: zotprime-k8s
spec:
    rules:
        - host: localhost
          http:
            paths:
                - backend:
                    service:
                        name: app-zotero-stream-server
                        port:
                            name: port-81
                  path: /app-zotero-stream-server
                  pathType: Prefix
                - backend:
                    service:
                        name: app-tinymce-clean-server
                        port:
                            name: port-16342
                  path: /app-tinymce-clean-server
                  pathType: Prefix
                - backend:
                    service:
                        name: db-zotprime-minio
                        port:
                            name: port-8080
                  path: /
                  pathType: Prefix
                - backend:
                    service:
                        name: app-zotprime
                        port:
                            name: port-8080
                  path: /
                  pathType: Prefix
status:
    loadBalancer: {}

...
