apiVersion: v1
kind: Service
metadata:
  labels:
    apps: dataserver
  name: dataserver
  namespace: zotprime
spec:
  ports:
    - name: port-80
      port: 80
      targetPort: 80
    - name: port-8082
      port: 8082
      targetPort: 8082
  selector:
    apps: zotprime-dataserver
  type: ClusterIP
status:
  loadBalancer: {}
