apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: zotprime-dataserver
  name: zotprime-dataserver
  namespace: zotprime
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: zotprime-dataserver
  strategy: {}
  template:
    metadata:
      labels:
        apps: zotprime-dataserver
      name: zotprime-dataserver
    spec:
      containers:
        - image: uniuu/zotprime-dataserver:2.6.1-rc
          imagePullPolicy: Always
          name: zotprime-dataserver
          ports:
            - containerPort: 80
#            - containerPort: 8082
          env:
            - name: DSURI
              value: http://api.projectdev.net/
            - name: S3POINTURI
              value: s3min.projectdev.net
          resources:
            limits:
              memory: 256Mi
              cpu: "0.1"
      priorityClassName: low-priority
      restartPolicy: Always
      hostAliases:
        - ip: "10.30.11.11"
          hostnames:
          - "s3min.projectdev.net"
      securityContext: {}
status: {}
