apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bucketsstore-vol
  namespace: zotprime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo