apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: zotprime-streamserver
  name: zotprime-streamserver
  namespace: zotprime
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: zotprime-streamserver
  strategy: {}
  template:
    metadata:
      labels:
        apps: zotprime-streamserver
      name: zotprime-streamserver
    spec:
      containers:
        - image: uniuu/zotprime-streamserver:2.6.1-rc
          name: zotprime-streamserver
          ports:
            - containerPort: 81           
          resources:
            limits:
              memory: 256Mi
              cpu: "0.5"
          livenessProbe:
            tcpSocket:
              port: 81
            initialDelaySeconds: 15
            periodSeconds: 20
      priorityClassName: medium-priority      
      restartPolicy: Always
      securityContext: {}
status: {}
