name: Build All Images via Docker Compose

on:
  push:
    paths:
      - '.github/workflows/build-all-images.yml'
      - '*.Dockerfile'
      - '*.dockerignore'
      - 'docker-compose-dev.yml'
    branches: [ "development" ]

  pull_request:
    branches: [ "development" ]
    paths:
      - '.github/workflows/build-all-images.yml'
      - '*.Dockerfile'
      - '*.dockerignore'
      - 'docker-compose-dev.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap config
        run: cp .env_example .env
      - name: Build the stack
        run: BUILDKIT_PROGRESS=plain docker compose -f docker-compose-dev.yml build