name: Build Streamserver Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - stack/stream-server/**
      - .github/workflows/build-streamserver-image.yml
    branches: [ "development" ]

  pull_request:
    branches: [ "development" ]
    paths:
      - stack/stream-server/**
      - .github/workflows/build-streamserver-image.yml


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init stack/stream-server/stream-server
    - name: Build the Streamserver Docker Image
#      working-directory: ./stream-server
      run: |
         cd stack/stream-server
         DOCKER_BUILDKIT=1 docker build . --progress=plain --file sts.Dockerfile --tag zotprime-streamserver:$(date +%s)
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        file: Dockerfile
