name: Build Dataserver Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - stack/dataserver/**
      - .github/workflows/build-dataserver-image.yml
    branches: [ "development" ]

  pull_request:
    branches: [ "development" ]
    paths:
      - stack/dataserver/**
      - .github/workflows/build-dataserver-image.yml
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init stack/dataserver/dataserver
    - 
      name: Build the Dataserver Docker image
      run: |
        cd stack/dataserver
        DOCKER_BUILDKIT=1 docker build . --progress=plain --file ds.Dockerfile --tag zotprime-dataserver:$(date +%s)