name: Dataserver Image CI

on:
  push:
    paths:
      - docker/dataserver/**
      - ds.Dockerfile
      - .github/workflows/dataserver-image.yml
    branches: [ "development" ]

  pull_request:
    branches: [ "development" ]
    paths:
      - docker/dataserver/**
      - ds.Dockerfile
      - .github/workflows/dataserver-image.yml
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ds.Dockerfile --tag zotprime-dataserver:$(date +%s)