name: Push All Images To Dockerhub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref:  production
          fetch-depth: 0
      - 
        name: Set variables
        run: echo "VERSION=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - 
        name: Test
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}
          echo $(git describe --tags --abbrev=0)
          echo $(git describe $(git rev-parse HEAD) --abbrev=0)
          echo $(git describe --tags `git rev-list --tags --max-count=1`)

#        run: |
#            VER=$(cat VERSION)
#            echo "VERSION=$VER" >> $GITHUB_ENV
#      - 
#        name: Bootstrap config
#        run: cp .env_example .env
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}


      -
        run: git checkout production
      -
        name: Build and push dataserver
        uses: docker/build-push-action@v5
        with:
          context: ./stack/dataserver
          file: stack/dataserver/ds.Dockerfile
          push: false
          tags: uniuu/dataserver:${{ env.VERSION }}
