name: Push All Images To Dockerhub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref:  production
          fetch-depth: 0
      - 
        name: Set variables
        run: echo "VERSION=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - 
        name: Test
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}
          echo $(git describe --tags --abbrev=0)
          echo $(git describe $(git rev-parse HEAD) --abbrev=0)
          echo $(git describe --tags `git rev-list --tags --max-count=1`)

#        run: |
#            VER=$(cat VERSION)
#            echo "VERSION=$VER" >> $GITHUB_ENV
#      - 
#        name: Bootstrap config
#        run: cp .env_example .env
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}

      -
        run: | 
           git checkout production
           git submodule update --init --recursive --remote stack/tinymce-clean-server/tinymce-clean-server
           git submodule update --init --recursive --remote stack/stream-server/stream-server
           git submodule update --init --recursive --remote stack/dataserver/dataserver
      -
        name: Build and push dataserver
        uses: docker/build-push-action@v5
        with:
          context: ./stack/dataserver
          file: stack/dataserver/ds.Dockerfile
          push: true
          tags: uniuu/zotprime-dataserver:${{ env.VERSION }}

      -
        name: Build and push stream-server
        uses: docker/build-push-action@v5
        with:
          context: ./stack/stream-server
          file: stack/stream-server/sts.Dockerfile
          push: true
          tags: uniuu/zotprime-streamserver:${{ env.VERSION }}

      -
        name: Build and push db
        uses: docker/build-push-action@v5
        with:
          context: ./stack/db
          file: stack/db/db.Dockerfile
          push: true
          tags: uniuu/zotprime-db:${{ env.VERSION }}

      -
        name: Build and push localstack
        uses: docker/build-push-action@v5
        with:
          context: ./stack/localstack
          file: stack/localstack/ls.Dockerfile
          push: true
          tags: uniuu/zotprime-localstack:${{ env.VERSION }}

      -
        name: Build and push memcached
        uses: docker/build-push-action@v5
        with:
          context: ./stack/memcached
          file: stack/memcached/m.Dockerfile
          push: true
          tags: uniuu/zotprime-memcached:${{ env.VERSION }}

      -
        name: Build and push elasticsearch
        uses: docker/build-push-action@v5
        with:
          context: ./stack/elasticsearch
          file: stack/elasticsearch/es.Dockerfile
          push: true
          tags: uniuu/zotprime-elasticsearch:${{ env.VERSION }}

      -
        name: Build and push minio
        uses: docker/build-push-action@v5
        with:
          context: ./stack/minio
          file: stack/minio/minio.Dockerfile
          push: true
          tags: uniuu/zotprime-minio:${{ env.VERSION }}

      -
        name: Build and push miniomc
        uses: docker/build-push-action@v5
        with:
          context: ./stack/minio
          file: stack/minio/miniomc.Dockerfile
          push: true
          tags: uniuu/zotprime-miniomc:${{ env.VERSION }}

      -
        name: Build and push phpmyadmin
        uses: docker/build-push-action@v5
        with:
          context: ./stack/phpmyadmin
          file: stack/phpmyadmin/pa.Dockerfile
          push: true
          tags: uniuu/zotprime-phpmyadmin:${{ env.VERSION }}

      -
        name: Build and push redis
        uses: docker/build-push-action@v5
        with:
          context: ./stack/redis
          file: stack/redis/r.Dockerfile
          push: true
          tags: uniuu/zotprime-redis:${{ env.VERSION }}


      -
        name: Build and push tinymce-clean-server
        uses: docker/build-push-action@v5
        with:
          context: ./stack/tinymce-clean-server
          file: stack/tinymce-clean-server/tmcs.Dockerfile
          push: true
          tags: uniuu/zotprime-tinymceclean:${{ env.VERSION }}