name: Push updated submodule zotero-standalone-build to ZotPrime

on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:  # click the button on Github repo!
permissions:
  contents: write
jobs:
  sync-fork:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: uniuuu/zotero-standalone-build
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: fregante/setup-git-user@v2
      - name: change version
        run: |
          git remote add upstream https://github.com/zotero/zotero-standalone-build.git
          git fetch upstream
          git checkout master
          git rebase upstream/master
          git push origin master
