name: Push updated submodule to ZotPrime CI

on: [repository_dispatch]


jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.receiver.outputs.SEMVER }}
    steps:

      - name: A event received
        id: receiver
        run: |
          echo "payload Foo '${{ github.event.client_payload.semver }}'"
          echo "payload '${{ toJson(github.event.client_payload) }}'"
          SEMVER=${{ github.event.client_payload.semver }}


  push_to_remote:
    needs: check_tag
    runs-on: ubuntu-latest
#    container: pandoc/latex 

#    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --remote client/zotero-build


      - uses: stefanzweifel/git-auto-commit-action@v4

  #    - name: Push tag
  #      uses: 'rui-costa/action-automatic-semver-releases@1.1.1'
  #      with:
  #        TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
  #        SEMVER: '${{ needs.check_tag.outputs.output1 }}'
#          LABEL: '${{ github.event.inputs.label }}'

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          default_bump: ${{ needs.check_tag.outputs.output1 }}
          release_branches: new_dev
          append_to_pre_release_tag: false