name: Push updated submodule zotero-standalone-build to ZotPrime

on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:  # click the button on Github repo!
permissions:
  contents: write
jobs:
  sync-fork:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: uniuuu/zotero-standalone-build
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: fregante/setup-git-user@v2
      - name: change version
        run: |
          git remote add upstream https://github.com/zotero/zotero-standalone-build.git
          git fetch upstream
          git checkout master
          git rebase upstream/master
          git push origin master

  update-submodule:
    runs-on: ubuntu-latest
    steps:

      - name: Semver
        id: receiver
        run: |
          echo "payload Foo '${{ github.event.client_payload.semver }}'"
          echo "payload '${{ toJson(github.event.client_payload) }}'"
          echo "SEMVER=${{ github.event.client_payload.semver }}" >> $GITHUB_ENV
          if [ $SEMVER="path" ]; then commit=fix; else if [ $SEMVER="minor" ]; then commit=feat; else commit='BREAKING CHANGE'; fi fi;
          echo "message=$commit" >> $GITHUB_ENV
        

       
      - name: Print1 
        run: |
          echo $SEMVER
          echo ${{ env.SEMVER }}
  

        
      - name: print2
        run: | 
           echo $message
           echo ${{ env.message }}
  

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --remote client/zotero-standalone-build
   
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            # Optional. Commit message for the created commit.
            # Defaults to "Apply automatic changes"
          commit_message: ${{ env.message }}
  
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          default_bump: ${{ env.SEMVER }}
          release_branches: development
          append_to_pre_release_tag: false