apiVersion: v1
kind: Service
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-elasticsearch
  labels:
    apps: elasticsearch
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elasticsearch.type }}
  selector:
    apps: zotprime-elasticsearch
  {{- include "zotprime-k8s.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.elasticsearch.ports | toYaml | nindent 2 -}}