apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-minio-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  secret.txt: {{ required "minioSecret.secretTxt is required" .Values.minioSecret.secretTxt
    | b64enc | quote }}
type: Opaque