apiVersion: v1
kind: Service
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-mysql
  labels:
    apps: mysql
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: {{ .Values.mysql.type }}
  selector:
    apps: zotprime-db
  {{- include "zotprime-k8s.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mysql.ports | toYaml | nindent 2 -}}