apiVersion: v1
kind: Service
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-tinymceclean
  labels:
    apps: tinymceclean
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tinymceclean.type }}
  selector:
    apps: zotprime-tinymceclean
  {{- include "zotprime-k8s.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.tinymceclean.ports | toYaml | nindent 2 -}}